/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insertion_sort_emulator;

import javax.swing.*;
import java.awt.*;

/**
 * @author Carl
 */
public class SortFrontPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(SortFrontPage.class.getName());

    public SortFrontPage() {
        initUI();
    }

    private void initUI() {
        setTitle("Insertion Sort Emulator");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(800, 500);
        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);

        //Background
        JPanel bgPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                GradientPaint gp = new GradientPaint(
                        0, 0, new Color(25, 24, 59),
                        getWidth(), getHeight(), new Color(255, 179, 71));
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        bgPanel.setBounds(0, 0, 800, 500);
        bgPanel.setLayout(null);
        add(bgPanel);
        
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(new Color(255, 255, 255, 230));
        card.setBounds(200, 60, 400, 380); // slightly taller
        card.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        card.setOpaque(true);
        bgPanel.add(card);

        //Title
        JLabel title = new JLabel("Insertion Sort Emulator", SwingConstants.CENTER);
        title.setFont(new Font("Segoe UI Semibold", Font.BOLD, 24));
        title.setForeground(new Color(25, 24, 59));
        title.setBounds(0, 20, 400, 40);
        card.add(title);

        //Start Simulation Button
        JButton startButton = new JButton("Start Simulation");
        startButton.setFont(new Font("Segoe UI Semibold", Font.BOLD, 16));
        startButton.setBounds(100, 140, 200, 45);
        startButton.setBackground(new Color(25, 24, 59));
        startButton.setForeground(Color.WHITE);
        startButton.setFocusPainted(false);
        startButton.setBorder(BorderFactory.createEmptyBorder());
        startButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                startButton.setBackground(new Color(40, 38, 90));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                startButton.setBackground(new Color(25, 24, 59));
            }
        });

        startButton.addActionListener(e -> {
            new SortSimulationPage().setVisible(true);
            dispose();
        });
        card.add(startButton);

        // Footer
        JLabel credits = new JLabel(
                "<html><center>"
                        + "<b>Developed by:</b><br>"
                        + "<span style='color:#19183b;font-weight:bold;'>Group 9</span><br>"
                        + "<span style='color:#19183b;font-style:italic;'>Carl Joseph F. Marquez</span><br>"
                        + "<span style='color:#19183b;font-style:italic;'>Shane Ashley D. Atajar</span><br>"
                        + "<span style='color:#19183b;font-style:italic;'>Klevyrie F. Sale</span><br>"
                        + "<span style='color:#19183b;font-style:italic;'>ITE 031 - SOUTH-3</span>"
                        + "</center></html>",
                SwingConstants.CENTER
        );
        credits.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        credits.setForeground(new Color(50, 50, 50));
        credits.setBounds(0, 260, 400, 100); // moved down + taller
        card.add(credits);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new SortFrontPage().setVisible(true));
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
